main: me.markeh.factionsplus.FactionsPlus
name: FactionsPlus
version: 2.0.0-beta3
website: http://ma.rkhugh.es/factionsplus
authors: [MarkehMe]
description: §eFactionsPlus extends on-top of Factions to provide more features. §aMarkehMe §eis the lead programmer. See §bhttp://ma.rkhugh.es/factionsplus§e for more information.
softdepend: [Factions, Factions26Patches]
permissions:
  factionsplus.rules: {description: add, delete, and view faction rules, default: false}
  factionsplus.chests: {description: use and set faction chests, default: false}
  factionsplus.jail: {description: set and create jails, and jail players in your faction, default: false}
  factionsplus.reload: {description: reload factions plus, default: false}
  factionsplus.managewarps: {description: manage faction warps, default: false}
  factionsplus.commandblockbypass: {description: bypass command block on radius feature, default: false}
  factionsplus.setwarp: {description: allows managing warps, default: false}
  factionsplus.warp: {description: allows using warps, default: false}
  factionsplus.disguseanywhere: {description: allows using disguise plugins anywhere, default: false}
  factionsplus.cannonsanywhere: {description: allows using cannons anywhere, default: false}
  factionsplus.announce: {description: allow using announcements, default: false}
  factionsplus.togglescoreboard: {description: allows using the scoreboard sub command, default: true} 